
# Generated by Django 5.2 on 2025-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
    ]
# Generated by Django 5.2.5 on 2025-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
    ]
