# Generated by Django 5.2.5 on 2025-08-14 19:42


# Generated by Django 5.2 on 2025-08-14 19:52

# Generated by Django 5.2.5 on 2025-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]

# Generated by Django 5.2.5 on 2025-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]

