# Generated by Django 5.2.5 on 2025-10-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
        ('materia', '0002_alter_materia_anio_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('materia', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
