# Generated by Django 5.2.5 on 2025-10-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_alter_horario_options_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
    ]
