
# Generated by Django 5.2.5 on 2025-08-11 21:12


# Generated by Django 5.2.2 on 2025-08-11 21:15
# Generated by Django 5.2.5 on 2025-08-11 21:12



from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(

            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),

            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),

            ],
        ),
    ]
