# Generated by Django 5.2.5 on 2025-09-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='justificación',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='justificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='materia.materia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
