# Generated by Django 5.2.5 on 2025-10-20 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesorado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.CharField(choices=[('1', '1º Año'), ('2', '2º Año'), ('3', '3º Año'), ('4', '4º Año')], default='1', max_length=10)),
                ('profesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='profesorado.profesorado')),
            ],
        ),
    ]
